version: '3'

services:

  lb:
    image: nginx:1.13-alpine
    ports:
      - "3000:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile.full
    image: todo
    depends_on:
      - db
    environment:
      DATABASE_URL: "mongodb://db:27017"
    restart: always

  db:
    image: mongo:3
    restart: always
    volumes:
      - data:/data/db

volumes:
  data:
