version: '3'

services:

  lb:
    image: nginx:1.13-alpine
    deploy:
      placement:
        constraints:
          - node.labels.zone == dmz
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 15s
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - /vagrant/todo/nginx-swarm.conf:/etc/nginx/nginx.conf:ro

  app:
    image: 192.168.50.4:443/todo
    depends_on:
      - db
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 75s
    environment:
      DATABASE_URL: "mongodb://db:27017"

  db:
    image: mongo:3
    deploy:
      placement:
        constraints:
          - node.labels.type == storage
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 15s
    volumes:
      - data:/data/db

volumes:
  data:
